### ISSUE TITLE
Dataset shape mismatch

### ISSUE THREAD

**Issue by qiuchengjian** [NUBagciLab/PaNSegNet#1]
in the folder imagesTr, the shape of NYU_0029_0000.nii.gz( the shape of (40, 240, 320, 2)) is not matched with the shape of NYU_0029_0000.nii.gz(the shape of (40, 240, 320)) in the folder labelsTr

**Comment by ulasbagci** [comment]
Can you guys check ?

**Comment by freshman97** [comment]
@qiuchengjian Hello, qiucheng. We double-checked the data and confirmed that "NYU_0029" has a shape-matching problem. We have updated the data in the OSF driver accordingly and thank you for raising this problem.
