### ISSUE TITLE
software_dont_infere

### ISSUE THREAD

**Issue by bertoldp** [NUBagciLab/PaNSegNet#3]
Hey tried out the software download was successful but it doesnt infere on my CT any ideas what I might be doing wrong?

**Comment by ulasbagci** [comment]
Tell us more about this,
What do you mean “does not interfere” ?
Is your images in correct format?

Ulas Bagci, Ph.D.,
Associate Professor, 
Machine & Hybrid Intelligence Lab,
Department of Radiology, Feinberg School of Medicine, 
Department of Biomedical Engineering (Courtesy),
Department of Electrical and Computer Engineering (Courtesy),
Northwestern University,
737 N. Michigan Avenue Suite 1600,
Chicago, IL 60611, USA
Phone: +1 312-694-4951
Cell: +1 240 383 8587
Permanent zoom link: https://northwestern.zoom.us/my/bagci <https://urldefense.com/v3/__https://northwestern.zoom.us/my/bagci__;!!Dq0X2DkFhyF93HkjWTBQKhk!U_Q9GlZi9jt5GVM9USLh7tmmYnpakorFLc0W6P3j3bRJgUqCgp8XrDL87SNzQM1NoNDxM5WuighbWtWGd1Rs7A$>
Web: www.bagcilab.com <https://urldefense.com/v3/__http://www.bagcilab.com__;!!Dq0X2DkFhyF93HkjWTBQKhk!U_Q9GlZi9jt5GVM9USLh7tmmYnpakorFLc0W6P3j3bRJgUqCgp8XrDL87SNzQM1NoNDxM5WuighbWtVfIlLZPA$>

**Comment by bertoldp** [comment]
So the scans should be in the correct format
.nii.gz

What I experience is the following:

I use cpu but even after 30 mins there's no result, when I click start I gives back the original scan without any inference on it and I can scroll through it.

I might try the python set up

Do you have a detailed tutorial on it and how to set it up just for inference?

**Comment by ulasbagci** [comment]
Not sure if CPU can be used, GPU is easier and efficient.
Zheyuan is cc’ed here for the response.

Ulas

**Comment by freshman97** [comment]
> So the scans should be in the correct format .nii.gz
> 
> What I experience is the following:
> 
> I use cpu but even after 30 mins there's no result, when I click start I gives back the original scan without any inference on it and I can scroll through it.
> 
> I might try the python set up
> 
> Do you have a detailed tutorial on it and how to set it up just for inference?

Yes, you can run it on the CPU as long as you have enough large RAM, as we recommended in the [guidance](https://github.com/NUBagciLab/PaNSegNet/blob/master/software/guidance.md).

**Comment by bertoldp** [comment]
How much does that increase the processing time?


If I go to start in the program and it gives back my CT scan and I can still scroll through does this mean it still inferes?

**Comment by freshman97** [comment]
Typically, the segmentation can be finished in 4 minutes on the CPU; if it is longer, there should be one problem: CPU RAM is not large enough to support the postprocessing.

**Comment by bertoldp** [comment]
Oh okay I have a 128GB GPU so in theory it should work
If I selected start and I can still scroll through it doesn't mean that it isn't inferring right?

Do you have some kind of example workflow for set up in python in an ipynb

**Comment by freshman97** [comment]
Sorry for the late reply, yes 128GB CPU should work. If I selected start you can still scroll it while it is segmenting, but it might take a while for the segmentation.

We will try to add one ipynb file for the tutorial in the future.

**Comment by bertoldp** [comment]
hey finally got it replacing the original nnUNet with yours worked
